function fig = uiViewPanel()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load uiViewPanel

h0 = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'CreateFcn','uiViewPanelCreateFnc', ...
	'FileName','C:\usr\ponti\matlab\gui\viewPanel\uiViewPanel.m', ...
	'MenuBar','none', ...
	'Name','View Panel', ...
	'NumberTitle','off', ...
	'PaperPosition',[148.5 229.5 315 333.75], ...
	'PaperUnits','points', ...
	'Position',[272 200 420 445], ...
	'ResizeFcn','VPanelResize(gcbf,[0 20 0 0])', ...
	'Tag','UIVIEWPANEL', ...
	'ToolBar','none');
h1 = uimenu('Parent',h0, ...
	'Callback','uiViewMenuFileFnc', ...
	'Label','&File', ...
	'Tag','UIVIEWMENU_FILE');
h2 = uimenu('Parent',h1, ...
	'Callback',mat1, ...
	'Label','&Open ...', ...
	'Tag','UIVIEWMENU_FILE_OPEN', ...
	'UserData','12');
h2 = uimenu('Parent',h1, ...
	'Label','&Save ...', ...
	'Tag','UIVIEWMENU_FILE_SAVE', ...
	'UserData','[ ]');
h3 = uimenu('Parent',h2, ...
	'Callback','uiViewMenuSaveFnc ', ...
	'Label','8 bit', ...
	'Tag','UIVIEWMENU_FILE_SAVE_8bit', ...
	'UserData','8bit');
h3 = uimenu('Parent',h2, ...
	'Callback','uiViewMenuSaveFnc', ...
	'Label','16 bit', ...
	'Tag','UIVIEWMENU_FILE_SAVE_16bit', ...
	'UserData','16bit');
h2 = uimenu('Parent',h1, ...
	'Label','Tiff Options', ...
	'Separator','on', ...
	'Tag','UIVIEWMENU_FILE_OPTIONS', ...
	'UserData','[ ]');
h3 = uimenu('Parent',h2, ...
	'Callback','uiSetTiffOptions;', ...
	'Label','Auto search (simple)', ...
	'Tag','UIVIEWMENU_FILE_OPTIONS_auto_default', ...
	'UserData','11');
h3 = uimenu('Parent',h2, ...
	'Callback','uiSetTiffOptions;', ...
	'Checked','on', ...
	'Label','Auto search (smart)', ...
	'Tag','UIVIEWMENU_FILE_OPTIONS_auto_smart', ...
	'UserData','12');
h3 = uimenu('Parent',h2, ...
	'Callback','uiSetTiffOptions;', ...
	'Label','8 bit', ...
	'Separator','on', ...
	'Tag','UIVIEWMENU_FILE_OPTIONS_8', ...
	'UserData','20');
h3 = uimenu('Parent',h2, ...
	'Callback','uiSetTiffOptions;', ...
	'Label','9 bit', ...
	'Tag','UIVIEWMENU_FILE_OPTIONS_9', ...
	'UserData','30');
h3 = uimenu('Parent',h2, ...
	'Callback','uiSetTiffOptions;', ...
	'Label','10 bit', ...
	'Tag','UIVIEWMENU_FILE_OPTIONS_10', ...
	'UserData','40');
h3 = uimenu('Parent',h2, ...
	'Callback','uiSetTiffOptions;', ...
	'Label','11 bit', ...
	'Tag','UIVIEWMENU_FILE_OPTIONS_11', ...
	'UserData','50');
h3 = uimenu('Parent',h2, ...
	'Callback','uiSetTiffOptions;', ...
	'Label','12 bit', ...
	'Tag','UIVIEWMENU_FILE_OPTIONS_12', ...
	'UserData','60');
h3 = uimenu('Parent',h2, ...
	'Callback','uiSetTiffOptions;', ...
	'Label','13 bit', ...
	'Tag','UIVIEWMENU_FILE_OPTIONS_13', ...
	'UserData','70');
h3 = uimenu('Parent',h2, ...
	'Callback','uiSetTiffOptions;', ...
	'Label','14 bit', ...
	'Tag','UIVIEWMENU_FILE_OPTIONS_14', ...
	'UserData','80');
h3 = uimenu('Parent',h2, ...
	'Callback','uiSetTiffOptions;', ...
	'Label','15 bit', ...
	'Tag','UIVIEWMENU_FILE_OPTIONS_15', ...
	'UserData','90');
h3 = uimenu('Parent',h2, ...
	'Callback','uiSetTiffOptions;', ...
	'Label','16 bit', ...
	'Tag','UIVIEWMENU_FILE_OPTIONS_16', ...
	'UserData','A0');
h2 = uimenu('Parent',h1, ...
	'Callback',mat2, ...
	'Label','Clear panel', ...
	'Separator','on', ...
	'Tag','UIVIEWMENU_FILE_CLEAR_PANEL');
h2 = uimenu('Parent',h1, ...
	'Callback',mat3, ...
	'Label','Close', ...
	'Tag','&FileClose1');
h1 = uimenu('Parent',h0, ...
	'Callback','uiViewMenuToolsFnc', ...
	'Label','&Tools', ...
	'Tag','UIVIEWMENU_TOOLS');
h2 = uimenu('Parent',h1, ...
	'Callback','uiViewMenuZoomFnc', ...
	'Label','&Zoom', ...
	'Tag','UIVIEWMENU_TOOLS_ZOOM');
h2 = uimenu('Parent',h1, ...
	'Callback','uiViewMenuZoomOutFnc', ...
	'Label','Zoom Out', ...
	'Tag','UIVIEWMENU_TOOLS_ZOOMOUT');
h2 = uimenu('Parent',h1, ...
	'Callback','uiViewMenuPixelFnc', ...
	'Label','Pixel &Value', ...
	'Tag','UIVIEWMENU_TOOLS_PIXEL');
h2 = uimenu('Parent',h1, ...
	'Callback','uiViewMenuColorFnc', ...
	'Label','&Gamma Correction', ...
	'Tag','UIVIEWMENU_COLORS');
h2 = uimenu('Parent',h1, ...
	'Callback','uiViewMenuScaleFnc', ...
	'Label','&Scalebar', ...
	'Tag','UIVIEWMENU_SCALE');
h1 = uimenu('Parent',h0, ...
	'Label','&Panels', ...
	'Tag','UIVIEWMENU_PANELS');
h2 = uimenu('Parent',h1, ...
	'Callback','uiViewMenuAcqFnc', ...
	'Label','&Acquire', ...
	'Tag','UIVIEWMENU_PANELS_ACQ');
h2 = uimenu('Parent',h1, ...
	'Callback','uiViewMenuSSDFnc', ...
	'Label','SSD T&rack', ...
	'Tag','UIVIEWMENU_PANELS_SSD');
h2 = uimenu('Parent',h1, ...
	'Callback',mat4, ...
	'Label','&Message Window', ...
	'Tag','MESSAGEWINDOWOPEN');
h1 = uimenu('Parent',h0, ...
	'Callback','uiViewMenuAnalyzeFnc', ...
	'Label','&Analyze', ...
	'Tag','UIVIEWMENU_ANALYZE');
h2 = uimenu('Parent',h1, ...
	'Callback','uiViewMenuProfileFnc', ...
	'Label','&Color Profile', ...
	'Tag','UIVIEWMENU_PROFILE');
h2 = uimenu('Parent',h1, ...
	'Callback','callGetStackBoundaries', ...
	'Label','&Get Stack Boundaries', ...
	'Tag','GETBOUNDARIES');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0 0 0], ...
	'ForegroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[10 0 250 10], ...
	'Style','text', ...
	'Tag','UIVIEWTEXT');
h1 = axes('Parent',h0, ...
	'Units','pixels', ...
	'Box','on', ...
	'CameraUpVector',[0 -1 0], ...
	'CameraUpVectorMode','manual', ...
	'CLimMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat5, ...
	'DataAspectRatioMode','manual', ...
	'Layer','top', ...
	'Position',[0 20 420 425], ...
	'Tag','Axes1', ...
	'TickDir','out', ...
	'TickDirMode','manual', ...
	'Visible','off', ...
	'WarpToFill','off', ...
	'WarpToFillMode','manual', ...
	'XColor',[0 0 0], ...
	'XLim',[0.5 400.5], ...
	'XLimMode','manual', ...
	'YColor',[0 0 0], ...
	'YDir','reverse', ...
	'YLim',[0.5 400.5], ...
	'YLimMode','manual', ...
	'ZColor',[0 0 0]);
h2 = image('Parent',h1, ...
	'CData',[], ...
	'CDataMapping','scaled', ...
	'Tag','Axes1Image1');
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[200.0226730310263 -5.7052505966588 2828.931544160121], ...
	'Tag','Axes1Text4', ...
	'VerticalAlignment','bottom');
set(get(h2,'Parent'),'Title',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[200.0226730310263 427.7076372315036 2828.931544160121], ...
	'Tag','Axes1Text3', ...
	'VerticalAlignment','cap', ...
	'Visible','off');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',mat6, ...
	'Rotation',90, ...
	'Tag','Axes1Text2', ...
	'VerticalAlignment','baseline', ...
	'Visible','off');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'Position',[400.5000000000001 402.8866348448688 2828.931544160121], ...
	'Tag','Axes1Text1', ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);
if nargout > 0, fig = h0; end
