function fig = uiSSDTrackPanel()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load uiSSDTrackPanel

h0 = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',[], ...
	'CreateFcn','uiSSDTrackPanelCreateFnc', ...
	'DeleteFcn','uiSSDTrackPanelDeleteFnc', ...
	'FileName','D:\usr\danuser\matlab\gui\ssdTrackPanel\uiSSDTrackPanel.m', ...
	'MenuBar','none', ...
	'MinColormap',0, ...
	'Name','SSD Track Panel', ...
	'NumberTitle','off', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[675 308 292 172], ...
	'Tag','UISSDTRACKPANEL', ...
	'ToolBar','none', ...
	'UserData',mat0);
h1 = uimenu('Parent',h0, ...
	'Callback','uiSSDTrackMenuFileFnc', ...
	'Label','&File', ...
	'Tag','UISSDTRACKMENU_FILE');
h2 = uimenu('Parent',h1, ...
	'Callback','uiSSDTrackMenuLoadStackFnc', ...
	'Label','Load Stack ...', ...
	'Tag','UISSDTRACKMENU_FILE_LOADSTACK');
h2 = uimenu('Parent',h1, ...
	'Callback','uiSSDTrackMenuDelStackFnc', ...
	'Enable','off', ...
	'Label','Delete Stack', ...
	'Tag','UISSDTRACKMENU_FILE_DELSTACK');
h1 = uimenu('Parent',h0, ...
	'Label','&Parameter', ...
	'Tag','UISSDTRACKMENU_PARAMETER');
h2 = uimenu('Parent',h1, ...
	'Callback','uiSSDTrackMenuSetFnc', ...
	'Label','Set', ...
	'Tag','UISSDTRACKMENU_PARAMETER_SET');
h2 = uimenu('Parent',h1, ...
	'Callback','uiSSDTrackMenuModeFnc', ...
	'Label','Mode', ...
	'Tag','UISSDTRACKMENU_PARAMETER_MODE');
h2 = uimenu('Parent',h1, ...
	'Callback','uiSSDTrackMenuResolFnc', ...
	'Label','Resolution', ...
	'Tag','UISSDTRACKMENU_PARAMETER_RESOL');
h2 = uimenu('Parent',h1, ...
	'Callback','uiSSDTrackMenuExcFnc', ...
	'Label','Excursion', ...
	'Tag','UISDDTRACKMENU_PARAMETER_EXC');
h1 = uimenu('Parent',h0, ...
	'Callback','uiSSDTrackMenuMasksFnc', ...
	'Label','&Masks', ...
	'Tag','UISSDTRACKMENU_MASK');
h2 = uimenu('Parent',h1, ...
	'Callback','uiSSDTrackMenuMasksFnc', ...
	'Checked','on', ...
	'Label','No Mask', ...
	'Tag','UISSDTRACKMENU_MASK_NO');
h2 = uimenu('Parent',h1, ...
	'Callback','uiSSDTrackMenuMasksFnc', ...
	'Label','Manual Center', ...
	'Tag','UISSDTRACKMENU_MASK_MANCTR');
h2 = uimenu('Parent',h1, ...
	'Callback','uiSSDTrackMenuMasksFnc', ...
	'Label','Manual Segment', ...
	'Tag','UISSDTRACKMENU_MASK_MANSEGM');
h2 = uimenu('Parent',h1, ...
	'Callback','uiSSDTrackMenuMasksFnc', ...
	'Label','DIC Line Full', ...
	'Tag','UISSDTRACKMENU_MASK_DICLF');
h2 = uimenu('Parent',h1, ...
	'Callback','uiSSDTrackMenuMasksFnc', ...
	'Label','DIC Line Adjacent', ...
	'Tag','UISSDTRACKMENU_MASK_DICAD');
h2 = uimenu('Parent',h1, ...
	'Callback','uiSSDTrackMenuMasksFnc', ...
	'Label','Pos Line Full', ...
	'Tag','UISSDTRACKMENU_MASK_POSLF');
h2 = uimenu('Parent',h1, ...
	'Callback','uiSSDTrackMenuMasksFnc', ...
	'Label','Pos Line Adjacent', ...
	'Tag','UISSDTRACKMENU_MASK_POSAD');
h1 = uimenu('Parent',h0, ...
	'Callback','uiSSDTrackMenuPropFnc', ...
	'Label','Pr&opagator', ...
	'Tag','UISSDTRACKMENU_PROP');
h2 = uimenu('Parent',h1, ...
	'Callback','uiSSDTrackMenuPropFnc', ...
	'Checked','on', ...
	'Label','Identity', ...
	'Tag','UISSDTRACKMENU_PROP_ID');
h2 = uimenu('Parent',h1, ...
	'Callback','uiSSDTrackMenuPropFnc', ...
	'Label','Position Identity', ...
	'Tag','UISSDTRACKMENU_PROP_IDNOSHAPE');
h2 = uimenu('Parent',h1, ...
	'Callback','uiSSDTrackMenuPropFnc', ...
	'Label','2 pt oscillation', ...
	'Tag','UISSDTRACKMENU_PROP_2PTOSCI');
h2 = uimenu('Parent',h1, ...
	'Callback','uiSSDTrackMenuPropFnc', ...
	'Enable','off', ...
	'Label','Properties ...', ...
	'Tag','UISSDTRACKMENU_PROP_PROPS');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','uiSSDTrackInitButtonPressFnc', ...
	'CreateFcn','uiSSDTrackInitButtonCreateFnc', ...
	'Enable','off', ...
	'ListboxTop',0, ...
	'Position',[10.5 107.25 54 18], ...
	'String','Init', ...
	'Tag','UISSDTRACKINITBUTTON');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','uiSSDTrackNextButtonPressFnc;', ...
	'CreateFcn','uiSSDTrackNextButtonCreateFnc', ...
	'Enable','off', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[10.5 84 54 16.5], ...
	'String','Next', ...
	'Tag','UISSDTRACKNEXTBUTTON');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'CreateFcn','uiSSDTrackLogEditCreateFnc', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[14.25 23.25 140.25 15], ...
	'String','d:\usr\danuser\matlab\ssdTrack.log', ...
	'Style','edit', ...
	'Tag','UISSDTRACKLOGEDIT');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','uiSSDTrackLogEditButtonPressFnc', ...
	'ListboxTop',0, ...
	'Position',[168.75 23.25 32.25 14.25], ...
	'String','...', ...
	'Tag','UISSDTRACKLOGEDITBUTTON');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[15 41.25 30 12.75], ...
	'String','Logfile:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'CreateFcn','uiSSDTrackWrapCheckCreateFnc', ...
	'Enable','off', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[70.5 87.75 8.25 9], ...
	'String','from Log', ...
	'Style','checkbox', ...
	'Tag','UISSDTRACKWRAPCHECK');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'CreateFcn','uiSSDTrackWrapTextCreateFnc', ...
	'Enable','off', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[86.25 85.5 24.75 12], ...
	'String','Wrap', ...
	'Style','text', ...
	'Tag','UISSDTRACKWRAPTEXT');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'Callback','uiSSDTrackVerboseCheckFnc', ...
	'CreateFcn','uiSSDTrackVerboseCheckCreateFnc', ...
	'ListboxTop',0, ...
	'Position',[130.5 111.75 8.25 8.25], ...
	'Style','checkbox', ...
	'Tag','UISSDTRACKVERBOSECHECK');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[141.75 111 34.5 9.75], ...
	'String','Verbose', ...
	'Style','text', ...
	'Tag','UISSDTRACKVERBOSETEXT');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'Callback','uiSSDTrackUpTemplateCheckFnc(''pressed'')', ...
	'CreateFcn','uiSSDTrackUpTemplateCheckFnc(''create'')', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[129.75 88.5 10.5 9], ...
	'Style','checkbox', ...
	'Tag','UISSDTRACKUPDATETIMGCHECK');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[142.5 84.75 51 14.25], ...
	'String','Update Tmpl', ...
	'Style','text', ...
	'Tag','UISSDTRACKUPDATETIMGTEXT');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','uiSSDTrackGoButtonPressFnc', ...
	'CreateFcn','uiSSDTrackGoButtonCreateFnc', ...
	'Enable','off', ...
	'ListboxTop',0, ...
	'Position',[10.5 59.25 53.25 16.5], ...
	'String','Go on!', ...
	'Tag','UISSDTRACKGOBUTTON');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'CreateFcn','uiSSDTrackFromLogCheckFnc(''create'')', ...
	'Enable','off', ...
	'ListboxTop',0, ...
	'Position',[70.5 106.5 45 15], ...
	'String','from Log', ...
	'Style','checkbox', ...
	'Tag','UISSDTRACKFROMLOGCHECK');
if nargout > 0, fig = h0; end
