function fig = ScaleOptions()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load ScaleOptions

h0 = figure('Units','points', ...
	'Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'MenuBar','none', ...
	'Name','Scale Options', ...
	'NumberTitle','off', ...
	'PointerShapeCData',mat1, ...
	'Position',[375.75 238.5 195.75 135.75], ...
	'Resize','off', ...
	'Tag','SCALE_OPTIONS');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[15 105 97.5 15], ...
	'String','One pixel corresponds to', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[165 105 17.25 15], ...
	'String','mu', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[120 105 30.75 15], ...
	'String','5', ...
	'Style','edit', ...
	'Tag','EditText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[15 75 56.25 15], ...
	'String','Scale length:', ...
	'Style','text', ...
	'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[165 75 17.25 15], ...
	'String','mu', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[120 75 30.75 15], ...
	'String','100', ...
	'Style','edit', ...
	'Tag','EditText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','SetScale', ...
	'ListboxTop',0, ...
	'Position',[75 15 45 15], ...
	'String','Set', ...
	'Tag','SET');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','SetScale', ...
	'ListboxTop',0, ...
	'Position',[135 15 45 15], ...
	'String','Close', ...
	'Tag','CLOSE');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[29.25 15 30 15], ...
	'String','Text:', ...
	'Style','text', ...
	'Tag','StaticText4');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[60 45 120 15], ...
	'Style','edit', ...
	'Tag','ADDTEXT');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[21 15 45 15], ...
	'String',['a';'b'], ...
	'Style','popupmenu', ...
	'Tag','PopupMenu1', ...
	'Value',1);
if nargout > 0, fig = h0; end
