function fig = GrabPanel(gbT)
%GRABTOOL/GRABPANEL(private)


h0 = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',[], ...
   'CreateFcn',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Create' 39 ')'],...
   'DeleteFcn',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Delete' 39 ')'],...
	'MenuBar','none', ...
	'MinColormap',0, ...
	'Name','Acquisition Panel', ...
	'NumberTitle','off', ...
   'Position',[699 284 316 325], ...
   'Resize','off', ...
   'Tag','GRABWINDOW',...
   'UserData',gbT);
h1 = uimenu('Parent',h0, ...
   'Callback',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Act' 39 ')'],...
	'Label','&File', ...
	'Tag','FILE_MENU');
h2 = uimenu('Parent',h1, ...
   'Callback',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Act' 39 ')'],...
	'Label','&Load ...', ...
	'Tag','LOAD_FILE');
h2 = uimenu('Parent',h1, ...
	'Label','Load Stack', ...
	'Tag','LOAD_STACK');
h3 = uimenu('Parent',h2, ...
   'Callback',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Act' 39 ')'],...
	'Label','Full ...', ...
	'Tag','LOADSTACK_FULL');
h3 = uimenu('Parent',h2, ...
   'Callback',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Act' 39 ')'],...
	'Label','Clipped ...', ...
	'Tag','LOADSTACK_CLIPPED');
h2 = uimenu('Parent',h1, ...
   'Callback',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Act' 39 ')'],...
	'Label','Load MPEG ...', ...
	'Tag','LOAD_MPEG');
h2 = uimenu('Parent',h1, ...
   'Callback',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Act' 39 ')'],...
	'Enable','off', ...
	'Label','&Save ...', ...
	'Tag','SAVE_FILE');
h2 = uimenu('Parent',h1, ...
   'Callback',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Act' 39 ')'],...
	'Enable','off', ...
	'Label','Save MPEG ...', ...
	'Tag','SAVE_MPEG');
h1 = uimenu('Parent',h0, ...
   'Callback',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Act' 39 ')'],...
	'Label','Fra&me', ...
	'Tag','FRAME_MENU');
h2 = uimenu('Parent',h1, ...
   'Callback',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Act' 39 ')'],...
	'Checked','on', ...
	'Label','Full', ...
	'Tag','FULL_FRAME');
h2 = uimenu('Parent',h1, ...
   'Callback',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Act' 39 ')'],...
	'Label','Select', ...
	'Tag','SELECT_SUBMENU');
h3 = uimenu('Parent',h2, ...
   'Callback',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Act' 39 ')'],...
	'Enable','off', ...
	'Label','Interactive', ...
	'Tag','FRAME_SELECT_INTERACTIVE');
h3 = uimenu('Parent',h2, ...
   'Callback',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Act' 39 ')'],...
	'Label','Panel', ...
	'Tag','FRAME_SELECT_PANEL');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
   'CreateFcn',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Create' 39 ')'],...
	'Enable','off', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[15 183.75 165 15], ...
	'String',gbT.acqDir, ...
	'Style','edit', ...
	'Tag','ACQ_DIR');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
   'CreateFcn',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Create' 39 ')'],...
	'Enable','off', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[15 147.75 165 15], ...
	'String',gbT.acqFile, ...
	'Style','edit', ...
	'Tag','ACQ_FILE');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'Callback',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Act' 39 ')'],...
   'CreateFcn',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Create' 39 ')'],...
	'Enable','off', ...
	'ListboxTop',0, ...
	'Position',[112.5 127.5 60 15], ...
	'String','Grab to File', ...
	'Tag','GRAB_TO_FILE');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'Callback',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Act' 39 ')'],...
   'CreateFcn',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Create' 39 ')'],...
	'Enable','off', ...
	'ListboxTop',0, ...
	'Position',[15 126.75 60 15], ...
	'String','Grab to View', ...
	'Tag','GRAB_TO_VIEW');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'Callback',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Act' 39 ')'],...
   'CreateFcn',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Create' 39 ')'],...
	'Enable','off', ...
	'ListboxTop',0, ...
	'Position',[15 106.5 60 15], ...
	'String','Grab Stack', ...
	'Tag','GRAB_STACK');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'Callback',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Act' 39 ')'],...
   'CreateFcn',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Create' 39 ')'],...
	'Enable','off', ...
	'ListboxTop',0, ...
	'Position',[15 84 60 15], ...
	'String',gbT.movie.buttonStr(1), ...
	'Tag','MOVIE_BUTTON');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'Callback',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Act' 39 ')'],...
   'CreateFcn',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Create' 39 ')'],...
	'Enable','off', ...
	'ListboxTop',0, ...
	'Position',[195 147.75 30 15], ...
	'String','...', ...
	'Tag','BROWSE');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
   'Callback',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Act' 39 ')'],...
	'Enable','off', ...
	'ListboxTop',0, ...
	'Max',50, ...
	'Min',30, ...
	'Position',[15 54 165 15], ...
	'SliderStep',[0.05 1], ...
	'Style','slider', ...
	'Tag','STACK_SLIDER', ...
	'Value',30);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
   'CreateFcn',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Create' 39 ')'],...
	'Enable','off', ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[112.5 105  30 15], ...
	'String',num2str(gbT.movie.time), ...
	'Style','edit', ...
	'Tag','ACQ_TIME');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
   'Callback',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Act' 39 ')'],...
	'Enable','off', ...
	'Position',[195 52.5 35 30], ...
	'Style','listbox', ...
	'Tag','STACK_LIST', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
   'Callback',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Act' 39 ')'],...
   'CreateFcn',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Create' 39 ')'],...
	'Enable','off', ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[195 105  30 15], ...
	'String',num2str(gbT.movie.fps), ...
	'Style','edit', ...
	'Tag','FRAMES_SEC');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[86.25 106.5 21 12], ...
	'String','[sec]:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[150 106.5 33.75 12], ...
	'String','[frm/sec]:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[183.75 126.75 11.25 15], ...
	'Style','checkbox', ...
	'Tag','SHOW_ACQ');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[198.75 129 24.75 11.25], ...
	'String','Show', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
   'Callback',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Act' 39 ')'],...
   'CreateFcn',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Create' 39 ')'],...
	'Enable','off', ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[112.5 84 29.25 15], ...
	'String',num2str(gbT.movie.repeat), ...
	'Style','edit', ...
	'Tag','MOVIE_REPEAT');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[150 86.25 30 11.25], ...
	'String','times', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[1 1 1], ...
   'Callback',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Act' 39 ')'],...
   'CreateFcn',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Create' 39 ')'],...
	'Enable','on', ...
	'Position',[105 221.25 120 15], ...
	'String',gbT.fg.typeList, ...
	'Style','popup', ...
	'Tag','FGTYPE', ...
	'Value',gbT.fg.active);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[11.25 222.75 82.5 11.25], ...
	'String','Select Framegrabber:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[15 202.5 75 11.25], ...
	'String','Acquisition Directory:', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[11.25 165 63.75 11.25], ...
	'String','Acquisition File:', ...
	'Style','text', ...
   'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[1 1 1], ...
   'Callback',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Act' 39 ')'],...
   'CreateFcn',['GrabPanelCB(get(gcf,' 39 'Userdata' 39 '),' 39 'Create' 39 ')'],...   
	'Enable','off', ...
	'ListboxTop',0, ...
	'Position',[129.75 19.5 50 18.75], ...
	'String',num2str(gbT.fg.shutterTime), ...
	'Style','edit', ...
	'Tag','SHUTTER_TIME');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[18.75 18.75 93.75 18.75], ...
	'String','Shutter Time in microsecs:', ...
	'Style','text', ...
	'Tag','StaticText4');
if nargout > 0, fig = h0; end
