function uiSSDTrackInitButtonPressFnc
% callback for the init button in the SSD track panel
pI = get(gcbf,'UserData');

if(isempty(pI.stack))
   [pI.tImg,pI.tPos,pI.tPosOff,pI.tPosRef,pI.patchDim,pI.trackCmd,pI.connectedView] = ...
      uiSSDTrackPanelInitTimg([],[],...
      pI.tImgMaskType,...
      pI.tImg,...
      pI.tPos,...
      pI.tPosRef,...
      pI.patchDim,...
      pI.trackCmd,...
      pI.connectedView);
   pI.nImgGrabbed = 1;
else
   [pI.tImg,pI.tPos,pI.tPosOff,pI.tPosRef,pI.patchDim,pI.trackCmd,pI.connectedView]= ...
      uiSSDTrackPanelInitTimg(pI.stack(:,:,1),pI.stackIndx(1),...
      pI.tImgMaskType,...
      pI.tImg,...
      pI.tPos,...
      pI.tPosRef,...
      pI.patchDim,...
   	pI.trackCmd,...
      pI.connectedView);
   pI.nextIndx = 2;
   
   if((pI.stackIndx(1)+1)~=pI.stackIndx(pI.nextIndx))
      % check whether the next index is the image after the first
      % (might have been changed through the wrapping)
      [pI.stack,pI.stackIndx,auxStackTot] = ...
         imreadstack(pI.stackName,...
         uiSSDTrackPanelGetDflt('maxImgInStack'));
   end;
   %% if there is a template initialzed in a stack then 
   %% give the user the option to set the wrap checkbox
   set(findobj(gcbf,'Tag','UISSDTRACKWRAPCHECK'),'Enable','on');
   set(findobj(gcbf,'Tag','UISSDTRACKWRAPTEXT'),'Enable','on');
end;

% set the displacement orientation in the template coordinate frame 
pI.tDispOri = pI.trackCmd.lori;

%pI.pos0 = pI.tPos;
%pI.posOff = pI.tPosOff;
initPropagator(getPropagatorType);
setPropagatorPosEstimate(pI.tPos+pI.tPosOff-1,[]);

set(gcbf,'UserData',pI);

% set the text of the view panel
textH = findobj(pI.connectedView,'Type','uicontrol','Tag','UIVIEWTEXT');
if(isempty(pI.stack))
   set(textH,'String',sprintf('1/1'));
else
   set(textH,'String',sprintf('%d/%d',pI.stackIndx(1),...
      pI.stackIndx(1)-1+pI.stackTot));
end;
set(textH,'Visible','on');


