function [ solutionT,residualsT,jacMatT  ] = leastSqGaussFit( x0,lb,ub,imageC,clusterPixels,psfSigma  )
%LEASTSQGAUSSFIT non-linear least squares fit for dectectSubResFEat3D
%   EHarry May 2012 

coder.extrinsic('optimset','lsqnonlin');

options = optimset('Jacobian','on',...
    'MaxFunEvals', 1e4, ...
    'MaxIter', 1e4, ...
    'Display', 'off', ...
    'TolX', 1e-6, ...
    'Tolfun', 1e-6);

[solutionT,~,residualsT,~,~,~,jacMatT] = ...
            lsqnonlin(@fitNGaussians3D_mexCode_mex,x0,lb,ub,options,imageC,...
            clusterPixels,psfSigma);


end

