function h =OptionWindow(sc)
%SCALE\OPTIONWINDOW (private)
%
% open the option window
%
% SYNOPSIS figHandle = OptionWindow(scale)
%
% c: 12/8/99	dT

% place window beside figure if possible
dum=get(0,'Units');
set(0,'Units','pixels');
screenSize = get(0,'ScreenSize');
set(0,'Units',dum);
dum=get(sc.figure,'Units');
set(sc.figure,'Units','pixels');
figPos=get(sc.figure,'Position');
set(sc.figure,'Units',dum);

%
winOffset = [8 20] ;
winWidth = 261;
winHeight = 181;
winPos = [0 0 winWidth winHeight];
winPos(2)= figPos(2)-(winHeight-figPos(4))+winOffset(2);
if(winPos(2)<0)
   winPos(2)=0;
end;

if((figPos(1)-winWidth-winOffset(1))>0)   
   winPos(1)=figPos(1)-winWidth-winOffset(1);
elseif((figPos(1)+figPos(3)+winWidth+winOffset(1))<screenSize(3))
   winPos(1)=figPos(1)+figPos(3)+winOffset(1);
else
   winPos(1)=winOffset(1);
end;

   h = figure('Units','pixels', ...
		'Color',[0.8 0.8 0.8], ...
		'MenuBar','none', ...
		'Name','Scalebar Options', ...
		'NumberTitle','off', ...
		'Position',winPos, ...
		'Resize','off', ...
      'Tag','SCALE_OPTIONS');
   axes('Units','points','Position',[0 0 195.75 135.75],'Visible','Off');
	uicontrol('Parent',h, ...
		'Units','points', ...
		'BackgroundColor',[0.8 0.8 0.8], ...
		'ListboxTop',0, ...
		'Position',[15 105 97.5 15], ...
		'String','One pixel corresponds to', ...
		'Style','text', ...
		'Tag','StaticText1');
%
   text(163,114,'\mum','Units','points','FontSize',8);
   
   uicontrol('Parent',h, ...
		'Units','points', ...
		'BackgroundColor',[1 1 1], ...
		'ListboxTop',0, ...
		'Position',[120 105 30.75 15], ...
		'String',sc.pixelSize, ...
		'Style','edit', ...
		'Tag','PIXELSIZE');
	uicontrol('Parent',h, ...
		'Units','points', ...
		'BackgroundColor',[0.8 0.8 0.8], ...
		'ListboxTop',0, ...
		'Position',[15 75 56.25 15], ...
		'String','Scale length:', ...
		'Style','text', ...
		'Tag','StaticText3');
   text(163,84,'\mum','Units','points','FontSize',8);
	uicontrol('Parent',h, ...
		'Units','points', ...
      'Callback',['ScaleCB(get(gcf,' 39 'Userdata' 39 '))'],...
		'BackgroundColor',[1 1 1], ...
		'ListboxTop',0, ...
		'Position',[120 75 30.75 15], ...
		'String',sc.length, ...
		'Style','edit', ...
		'Tag','LENGTH');
   uicontrol('Parent',h, ...
      'Units','points', ...
      'Callback',['ScaleCB(get(gcf,' 39 'Userdata' 39 '))'],...
		'ListboxTop',0, ...
		'Position',[75 15 45 15], ...
		'String','Set', ...
		'Tag','SET');
	uicontrol('Parent',h, ...
      'Units','points', ...
      'Callback',['ScaleCB(get(gcf,' 39 'Userdata' 39 '))'],...
		'ListboxTop',0, ...
		'Position',[135 15 45 15], ...
		'String','Close', ...
		'Tag','CLOSE');
	uicontrol('Parent',h, ...
		'Units','points', ...
		'BackgroundColor',[0.8 0.8 0.8], ...
		'ListboxTop',0, ...
		'Position',[15 45 30 15], ...
		'String','Text:', ...
		'Style','text', ...
		'Tag','StaticText4');
	uicontrol('Parent',h, ...
		'Units','points', ...
		'BackgroundColor',[1 1 1], ...
		'ListboxTop',0, ...
		'Position',[60 45 120 15], ...
		'String',sc.text, ...
		'Style','edit', ...
      'Tag','ADDTEXT');
   uicontrol('Parent',h, ...
		'Units','points', ...
		'ListboxTop',0, ...
		'Position',[15 15 45 15], ...
		'String',['white';'black'], ...
		'Style','popupmenu', ...
		'Tag','POPCOLOR', ...
		'Value',sc.color);
   
%associate scale with figure for callback functions
set(h,'UserData',sc);
