function F = nonLnFFun(x0,lb,ub,image,...
            clusterPixels,psfSigma)

optionsM = optimset('Jacobian','on',...
    'MaxFunEvals', 2, ...
    'MaxIter', 2, ...
    'Display', 'off', ...
    'TolX', 1e-6, ...
    'Tolfun', 1e-6);

x1 = ...
            lsqnonlin(@fitNGaussians3D_mexCode_mex,x0,lb,ub,optionsM,image,...
            clusterPixels,psfSigma);

F = fitNGaussians3D_mexCode_mex(x1,image,clusterPixels,psfSigma);
