function plot_prot_retro

% This function plots average protrusion and average retrograde flow as
% well as average protrusion and average shifted retrograde flow in two
% separate figures. To use the function you have to be in the subdirectory
% av_data under your merge directroy (/merge/av_data) where you have 
% generated by merging protrusion with retrograde flow. Once you are there,
% in the command line type the name of the function and the figures will be
% generated on screen as well as saved in the av_data directory. 
% 
% example type: plot_prot_retro
%
% Author: Mohsen Sabouri_Ghomi 9/13/07

load('av_prot_variables');
load('av_retro_variables');
load('av_shift_retro_variables');


layerplot(1:size(av_protrusion_n_time,2), av_protrusion_n_time,...
    1:size(av_protrusion_n_time,2), av_retrograde_flow_n_time, ...
    {'time (min)', 'Average Protrusion', ...
    'Average Retrograde Flow in LP'});
hgsave('prot_retro_flow');


layerplot(1:size(av_protrusion_n_time,2), av_protrusion_n_time,...
    1:size(av_protrusion_n_time,2), av_shift_retrograde_flow_n_time, ...
    {'time (min)', 'Average protrusion', ...
    'Average Retrograde Flow in Lamella'});
hgsave('prot_retro_s_flow');

end